name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build dependencies & wheels (Windows / amd64)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          python3 -m pip --disable-pip-version-check install cibuildwheel==1.6.1
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "*win_amd64"
          DISTUTILS_USE_SDK: 1
          MSSdk: 1

      - name: Install cibuildwheel & build wheels (Linux & MacOS)
        if: runner.os != 'Windows'
        run: |
          python3 -m pip --disable-pip-version-check install cibuildwheel==1.6.1
          python3 -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
